In [1]:
import pandas as pd
import altair as alt
import numpy as np
import geopandas as gpd
from vega_datasets import data  
import plotly.express as px

In [2]:
stateDF=pd.read_csv('assets/wb_state_temps.csv', header=1)
stateDF.columns

Index(['Unnamed: 0', 'United States', 'Alabama', 'Alaska', 'Arizona',
       'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object')

In [3]:
stateDF = stateDF.rename(columns = {stateDF.columns[0]:'Year'})
stateDF2=stateDF.drop(['United States'], axis=1)
# stateDF.iloc[::10,:]
display(stateDF2)

,Year,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
0,1901,16.58,-5.18,14.98,16.29,13.56,6.68,8.47,12.12,12.99,...,7.77,13.63,18.75,8.58,4.77,12.31,7.79,10.30,6.05,5.64
1,1902,17.77,-5.55,14.49,16.10,13.00,6.39,8.70,12.64,13.60,...,6.62,14.45,19.04,8.14,4.73,12.92,7.44,10.89,6.19,5.06
2,1903,17.07,-5.52,14.32,15.50,13.11,5.49,8.68,12.39,13.23,...,6.18,13.97,17.58,7.24,4.84,12.62,7.31,10.81,5.31,4.16
3,1904,17.50,-5.92,15.09,16.02,13.70,6.53,7.17,11.02,12.07,...,6.38,13.92,18.72,8.31,3.10,11.78,8.20,10.08,4.52,5.42
4,1905,17.35,-3.84,14.32,15.66,13.35,5.79,8.22,12.14,13.07,...,6.41,14.15,17.84,7.83,4.16,12.55,7.87,10.60,5.42,4.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2016,19.25,-1.36,16.84,18.04,15.08,7.92,11.71,14.21,15.08,...,9.41,16.10,20.05,9.42,7.27,14.44,9.64,12.61,8.13,6.63
116,2017,19.06,-2.71,17.31,17.79,15.08,7.95,11.22,14.29,15.25,...,8.64,15.90,20.17,9.68,6.80,14.53,8.55,12.55,7.55,6.12
117,2018,18.66,-2.20,16.96,16.87,14.97,7.51,11.09,14.00,14.93,...,7.36,15.43,19.51,9.53,6.71,14.16,9.17,12.15,6.62,5.59
118,2019,19.15,-1.27,16.03,16.96,14.52,6.62,10.73,14.30,15.40,...,6.66,15.85,19.47,8.35,6.22,14.71,8.31,12.61,6.14,4.66
119,2020,18.89,-3.85,17.01,17.08,15.18,7.75,11.76,14.72,15.71,...,8.79,15.57,20.01,9.49,7.38,14.80,9.13,12.64,7.54,6.25

In [4]:
state_dict={'year':[], 'state':[],'temperature':[]}
allstates = list(stateDF2.columns)
allstates.remove('Year')
# print(allstates)

allyears=stateDF2.Year.unique()

for year in allyears:
    for state in allstates:
        state_dict['year']+=[year]
        state_dict['state']+=[state]
        state_dict['temperature']+=[stateDF2.loc[(stateDF2.Year==year)][state].iloc[0]]
plotdf=pd.DataFrame(state_dict)
display(plotdf)

      year          state  temperature
0     1901        Alabama        16.58
1     1901         Alaska        -5.18
2     1901        Arizona        14.98
3     1901       Arkansas        16.29
4     1901     California        13.56
...    ...            ...          ...
6115  2020       Virginia        14.80
6116  2020     Washington         9.13
6117  2020  West Virginia        12.64
6118  2020      Wisconsin         7.54
6119  2020        Wyoming         6.25

[6120 rows x 3 columns]

In [5]:
def funcdelta(year1,year2,df):
    state_dict={'state':[],'temperature':[]}
    for state in df.state.unique():
        state_dict['state']+=[state]
        temp2=df.loc[(df.state==state) & (df.year==year2)].temperature.iloc[0]
        temp1=df.loc[(df.state==state) & (df.year==year1)].temperature.iloc[0]
        state_dict['temperature']+= [temp2 - temp1]
    return pd.DataFrame(state_dict)

In [6]:
display(funcdelta(1901,2020,plotdf))

                   state  temperature
0                Alabama         2.31
1                 Alaska         1.33
2                Arizona         2.03
3               Arkansas         0.79
4             California         1.62
5               Colorado         1.07
6            Connecticut         3.29
7               Delaware         2.60
8   District of Columbia         2.72
9                Florida         3.03
10               Georgia         2.47
11                Hawaii         2.68
12                 Idaho         0.69
13              Illinois         1.43
14               Indiana         1.75
15                  Iowa         1.06
16                Kansas         1.06
17              Kentucky         1.83
18             Louisiana         1.95
19                 Maine         2.16
20              Maryland         2.60
21         Massachusetts         3.13
22              Michigan         2.02
23             Minnesota         1.60
24           Mississippi         1.76
25              Missouri         0.73
26               Montana         0.63
27              Nebraska         1.17
28                Nevada         1.39
29         New Hampshire         2.72
30            New Jersey         3.10
31            New Mexico         1.48
32              New York         2.53
33        North Carolina         2.59
34          North Dakota         1.47
35                  Ohio         2.07
36              Oklahoma         0.63
37                Oregon         1.43
38          Pennsylvania         2.35
39          Rhode Island         3.40
40        South Carolina         2.51
41          South Dakota         1.02
42             Tennessee         1.94
43                 Texas         1.26
44                  Utah         0.91
45               Vermont         2.61
46              Virginia         2.49
47            Washington         1.34
48         West Virginia         2.34
49             Wisconsin         1.49
50               Wyoming         0.61

In [7]:
ansi = pd.read_csv('https://www2.census.gov/geo/docs/reference/state.txt', sep='|')
ansi.columns = ['id', 'abbr', 'state', 'statens']
ansi = ansi[['id', 'abbr', 'state']]
def mergeWansi(df):
    return pd.merge(df, ansi, how='left', on='state')
# plotdf = pd.merge(plotdf, ansi, how='left', on='state')
plotdf=mergeWansi(plotdf)
display(plotdf)

      year          state  temperature  id abbr
0     1901        Alabama        16.58   1   AL
1     1901         Alaska        -5.18   2   AK
2     1901        Arizona        14.98   4   AZ
3     1901       Arkansas        16.29   5   AR
4     1901     California        13.56   6   CA
...    ...            ...          ...  ..  ...
6115  2020       Virginia        14.80  51   VA
6116  2020     Washington         9.13  53   WA
6117  2020  West Virginia        12.64  54   WV
6118  2020      Wisconsin         7.54  55   WI
6119  2020        Wyoming         6.25  56   WY

[6120 rows x 5 columns]

In [8]:
display(plotdf)

      year          state  temperature  id abbr
0     1901        Alabama        16.58   1   AL
1     1901         Alaska        -5.18   2   AK
2     1901        Arizona        14.98   4   AZ
3     1901       Arkansas        16.29   5   AR
4     1901     California        13.56   6   CA
...    ...            ...          ...  ..  ...
6115  2020       Virginia        14.80  51   VA
6116  2020     Washington         9.13  53   WA
6117  2020  West Virginia        12.64  54   WV
6118  2020      Wisconsin         7.54  55   WI
6119  2020        Wyoming         6.25  56   WY

[6120 rows x 5 columns]

<b>This was the original plot I created. You can change the year under transform_lookup to see the temps in different years. It's not as beneficial because from year to year, it doesn't change enough to see anything significant since they're all going based off of 0 degrees celsius. </b>

In [9]:
states = alt.topo_feature(data.us_10m.url, feature='states')

base = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

chart = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color='temperature:Q',
    tooltip=['temperature:Q']
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(plotdf.loc[plotdf.year==1901], 'id', ['temperature'])
).properties(
    width=500,
    height=300
).project('albersUsa')


base + chart

alt.LayerChart(...)

<b>This is the final plot. It's the change in temperatures over time. I did from 1901 to 2020, but you can always change them if you want to play around with it under the funcdelta function. This shows which states have gotten hotter over the last 100 years and which haven't gotten as hot. We can always play around with the color scheme too if we want- it was blue like above but I thought the red was better with redder being hotter.</b>

In [10]:
base1 = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

deltdf=mergeWansi(funcdelta(1901,2020,plotdf))
display(deltdf)
chart1 = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color=alt.Color('temperature:Q',scale=alt.Scale(scheme='orangered')),
    tooltip=['temperature:Q']
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(deltdf, 'id', ['temperature'])
).properties(
    width=500,
    height=300
).project('albersUsa')

base1 + chart1

                   state  temperature  id abbr
0                Alabama         2.31   1   AL
1                 Alaska         1.33   2   AK
2                Arizona         2.03   4   AZ
3               Arkansas         0.79   5   AR
4             California         1.62   6   CA
5               Colorado         1.07   8   CO
6            Connecticut         3.29   9   CT
7               Delaware         2.60  10   DE
8   District of Columbia         2.72  11   DC
9                Florida         3.03  12   FL
10               Georgia         2.47  13   GA
11                Hawaii         2.68  15   HI
12                 Idaho         0.69  16   ID
13              Illinois         1.43  17   IL
14               Indiana         1.75  18   IN
15                  Iowa         1.06  19   IA
16                Kansas         1.06  20   KS
17              Kentucky         1.83  21   KY
18             Louisiana         1.95  22   LA
19                 Maine         2.16  23   ME
20              Maryland         2.60  24   MD
21         Massachusetts         3.13  25   MA
22              Michigan         2.02  26   MI
23             Minnesota         1.60  27   MN
24           Mississippi         1.76  28   MS
25              Missouri         0.73  29   MO
26               Montana         0.63  30   MT
27              Nebraska         1.17  31   NE
28                Nevada         1.39  32   NV
29         New Hampshire         2.72  33   NH
30            New Jersey         3.10  34   NJ
31            New Mexico         1.48  35   NM
32              New York         2.53  36   NY
33        North Carolina         2.59  37   NC
34          North Dakota         1.47  38   ND
35                  Ohio         2.07  39   OH
36              Oklahoma         0.63  40   OK
37                Oregon         1.43  41   OR
38          Pennsylvania         2.35  42   PA
39          Rhode Island         3.40  44   RI
40        South Carolina         2.51  45   SC
41          South Dakota         1.02  46   SD
42             Tennessee         1.94  47   TN
43                 Texas         1.26  48   TX
44                  Utah         0.91  49   UT
45               Vermont         2.61  50   VT
46              Virginia         2.49  51   VA
47            Washington         1.34  53   WA
48         West Virginia         2.34  54   WV
49             Wisconsin         1.49  55   WI
50               Wyoming         0.61  56   WY

alt.LayerChart(...)

In [23]:
base2 = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

deltdf=mergeWansi(funcdelta(1901,2020,plotdf))

chart2 = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color=alt.Color('temperature:Q',scale=alt.Scale(scheme='orangered'), title="Temperature"),
    tooltip=['temperature:Q']
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(deltdf, 'id', ['temperature'])
).properties(
    width=500,
    height=300
).project('albersUsa'
).properties(
    title='Temperature Change in Degrees Celsius from 1901 to 2020'
)

chart2

alt.Chart(...)

In [12]:
tempDF=pd.read_csv('assets/state_temps.csv')
display(tempDF)

         State  State Code  Deaths  Population        Crude Rate
0      Alabama           1     130    83992436               0.2
1      Arizona           4     876   109148430               0.8
2     Arkansas           5     160    51117937               0.3
3   California           6     712   657416771               0.1
4     Colorado           8      42    87509259                 0
..         ...         ...     ...         ...               ...
76       Texas          48     269   340322790               0.1
77        Utah          49      18    35128234  0.1 (Unreliable)
78    Virginia          51      50   121683012                 0
79  Washington          53      18    96320478  0.0 (Unreliable)
80   Wisconsin          55      58    98378433               0.1

[81 rows x 5 columns]

In [13]:
tempDF['Reliable']=tempDF['Crude Rate'].apply(lambda x: 0 if ('Unreliable' in x) else 1)
display(tempDF)

         State  State Code  Deaths  Population        Crude Rate  Reliable
0      Alabama           1     130    83992436               0.2         1
1      Arizona           4     876   109148430               0.8         1
2     Arkansas           5     160    51117937               0.3         1
3   California           6     712   657416771               0.1         1
4     Colorado           8      42    87509259                 0         1
..         ...         ...     ...         ...               ...       ...
76       Texas          48     269   340322790               0.1         1
77        Utah          49      18    35128234  0.1 (Unreliable)         0
78    Virginia          51      50   121683012                 0         1
79  Washington          53      18    96320478  0.0 (Unreliable)         0
80   Wisconsin          55      58    98378433               0.1         1

[81 rows x 6 columns]

In [14]:
tempDF['CrudeFloat']=tempDF['Crude Rate'].apply(lambda x: float(x.split(' ')[0]) if ('Unreliable' in x) else float(x))
display(tempDF)

,State,State Code,Deaths,Population,Crude Rate,Reliable,CrudeFloat
0,Alabama,1,130,83992436,0.2,1,0.2
1,Arizona,4,876,109148430,0.8,1,0.8
2,Arkansas,5,160,51117937,0.3,1,0.3
3,California,6,712,657416771,0.1,1,0.1
4,Colorado,8,42,87509259,0,1,0.0
...,...,...,...,...,...,...,...
76,Texas,48,269,340322790,0.1,1,0.1
77,Utah,49,18,35128234,0.1 (Unreliable),0,0.1
78,Virginia,51,50,121683012,0,1,0.0
79,Washington,53,18,96320478,0.0 (Unreliable),0,0.0
80,Wisconsin,55,58,98378433,0.1,1,0.1

In [15]:
tempDF['DPM']=tempDF.Deaths/tempDF.Population*1e6
tempDF['state']=tempDF['State']
display(tempDF)

,State,State Code,Deaths,Population,Crude Rate,Reliable,CrudeFloat,DPM,state
0,Alabama,1,130,83992436,0.2,1,0.2,1.547758,Alabama
1,Arizona,4,876,109148430,0.8,1,0.8,8.025768,Arizona
2,Arkansas,5,160,51117937,0.3,1,0.3,3.130017,Arkansas
3,California,6,712,657416771,0.1,1,0.1,1.083027,California
4,Colorado,8,42,87509259,0,1,0.0,0.479949,Colorado
...,...,...,...,...,...,...,...,...,...
76,Texas,48,269,340322790,0.1,1,0.1,0.790426,Texas
77,Utah,49,18,35128234,0.1 (Unreliable),0,0.1,0.512408,Utah
78,Virginia,51,50,121683012,0,1,0.0,0.410904,Virginia
79,Washington,53,18,96320478,0.0 (Unreliable),0,0.0,0.186876,Washington
80,Wisconsin,55,58,98378433,0.1,1,0.1,0.589560,Wisconsin

In [16]:
tempDF=tempDF[['state','Deaths','Reliable','DPM']]
# display(tempDF)
# tempDF['stateDeaths']=tempDF.groupby(['State'],as_index=False)#['Deaths'].sum()
cleanDF=pd.DataFrame(columns=tempDF.columns)
statelist=tempDF.state.unique()
for state in statelist:
    if len(tempDF.loc[tempDF.state==state])==1:
        cleanDF=pd.concat([cleanDF,tempDF.loc[tempDF.state==state]])
    else:
        tempstateDF=tempDF.loc[tempDF.state==state].reset_index(drop=True,inplace=False)
        # display(tempstateDF)
        stateDict={}
        stateDict['state']=[state]
        stateDict['Deaths']=[tempstateDF.Deaths.sum()]
        stateDict['Reliable']=[np.product(np.array(tempstateDF.Reliable))]
        stateDict['DPM']=[tempstateDF.DPM.mean()]
        cleanDF=pd.concat([cleanDF,pd.DataFrame(stateDict)])
        # tempstateDF['Deaths']=tempstateDF.groupby(['State'],as_index=False).Deaths.sum()
        # tempstateDF['Deaths']=tempstateDF['State'].apply(lambda x: if x==x tempstateDF['Deaths'].sum())
        # stateDict['DPM']=stateDict.groupby['State'],as_index=False)['DPM'].mean()
        # cleanDF=pd.concat([cleanDF,tempstateDF.loc[[0]]])
cleanDF.DPM=np.round_(cleanDF.DPM,decimals=2)
cleanDF.reset_index(drop=True, inplace=True)
        
display(cleanDF)

                   state Deaths Reliable   DPM
0                Alabama    190        1  1.14
1                Arizona   1179        1  6.10
2               Arkansas    308        1  3.11
3             California   1093        1  0.88
4               Colorado     42        1  0.48
5            Connecticut     14        0  0.22
6               Delaware     15        0  0.96
7   District of Columbia     40        0  1.71
8                Florida    394        1  0.65
9                Georgia    332        1  1.14
10                Hawaii     18        0  0.76
11                 Idaho     37        0  0.76
12              Illinois    427        1  0.93
13               Indiana    137        1  0.60
14                  Iowa    126        1  1.13
15                Kansas    237        1  2.37
16              Kentucky    139        1  0.91
17             Louisiana    225        1  1.36
18                 Maine     10        0  0.42
19              Maryland    162        0  0.80
20         Massachusetts     28        1  0.24
21              Michigan    128        1  0.35
22             Minnesota     57        1  0.61
23           Mississippi    175        1  1.66
24              Missouri    700        1  3.36
25               Montana     14        0  0.81
26              Nebraska     47        0  0.73
27                Nevada    251        1  3.18
28         New Hampshire     10        0  0.43
29            New Jersey    117        0  0.37
30            New Mexico     55        1  1.55
31              New York    314        1  0.45
32        North Carolina    206        1  0.66
33                  Ohio    185        1  0.44
34              Oklahoma    282        1  2.15
35                Oregon     65        1  0.52
36          Pennsylvania    290        1  0.63
37          Rhode Island     10        0  0.53
38        South Carolina    243        1  1.62
39          South Dakota     22        1  1.53
40             Tennessee    233        1  1.08
41                 Texas   1127        1  1.38
42                  Utah     37        0  0.46
43              Virginia    195        1  0.72
44            Washington     88        0  0.39
45         West Virginia     11        0  0.33
46             Wisconsin    152        1  0.76

In [17]:
wansi_cleanDF=mergeWansi(cleanDF)
display(wansi_cleanDF)

                   state Deaths Reliable   DPM  id abbr
0                Alabama    190        1  1.14   1   AL
1                Arizona   1179        1  6.10   4   AZ
2               Arkansas    308        1  3.11   5   AR
3             California   1093        1  0.88   6   CA
4               Colorado     42        1  0.48   8   CO
5            Connecticut     14        0  0.22   9   CT
6               Delaware     15        0  0.96  10   DE
7   District of Columbia     40        0  1.71  11   DC
8                Florida    394        1  0.65  12   FL
9                Georgia    332        1  1.14  13   GA
10                Hawaii     18        0  0.76  15   HI
11                 Idaho     37        0  0.76  16   ID
12              Illinois    427        1  0.93  17   IL
13               Indiana    137        1  0.60  18   IN
14                  Iowa    126        1  1.13  19   IA
15                Kansas    237        1  2.37  20   KS
16              Kentucky    139        1  0.91  21   KY
17             Louisiana    225        1  1.36  22   LA
18                 Maine     10        0  0.42  23   ME
19              Maryland    162        0  0.80  24   MD
20         Massachusetts     28        1  0.24  25   MA
21              Michigan    128        1  0.35  26   MI
22             Minnesota     57        1  0.61  27   MN
23           Mississippi    175        1  1.66  28   MS
24              Missouri    700        1  3.36  29   MO
25               Montana     14        0  0.81  30   MT
26              Nebraska     47        0  0.73  31   NE
27                Nevada    251        1  3.18  32   NV
28         New Hampshire     10        0  0.43  33   NH
29            New Jersey    117        0  0.37  34   NJ
30            New Mexico     55        1  1.55  35   NM
31              New York    314        1  0.45  36   NY
32        North Carolina    206        1  0.66  37   NC
33                  Ohio    185        1  0.44  39   OH
34              Oklahoma    282        1  2.15  40   OK
35                Oregon     65        1  0.52  41   OR
36          Pennsylvania    290        1  0.63  42   PA
37          Rhode Island     10        0  0.53  44   RI
38        South Carolina    243        1  1.62  45   SC
39          South Dakota     22        1  1.53  46   SD
40             Tennessee    233        1  1.08  47   TN
41                 Texas   1127        1  1.38  48   TX
42                  Utah     37        0  0.46  49   UT
43              Virginia    195        1  0.72  51   VA
44            Washington     88        0  0.39  53   WA
45         West Virginia     11        0  0.33  54   WV
46             Wisconsin    152        1  0.76  55   WI

In [18]:
locDF=pd.read_csv('assets/long_lat.csv')
# dcdict={'state':['District of Columbia'], 'latitude':[38.9072], 'longitude':[77.0369]}


# locDF=pd.concat([locDF,pd.DataFrame(dcdict)])

wansi_cleanDF=pd.merge(wansi_cleanDF,locDF,how='inner',left_on='state', right_on='state')
display(wansi_cleanDF)

             state Deaths Reliable   DPM  id abbr   latitude   longitude
0          Alabama    190        1  1.14   1   AL  32.318230  -86.902298
1          Arizona   1179        1  6.10   4   AZ  34.048927 -111.093735
2         Arkansas    308        1  3.11   5   AR  34.799999  -92.199997
3       California   1093        1  0.88   6   CA  36.778259 -119.417931
4         Colorado     42        1  0.48   8   CO  39.113014 -105.358887
5      Connecticut     14        0  0.22   9   CT  41.599998  -72.699997
6         Delaware     15        0  0.96  10   DE  39.000000  -75.500000
7          Florida    394        1  0.65  12   FL  27.994402  -81.760254
8          Georgia    332        1  1.14  13   GA  33.247875  -83.441162
9           Hawaii     18        0  0.76  15   HI  19.741755 -155.844437
10           Idaho     37        0  0.76  16   ID  44.068203 -114.742043
11        Illinois    427        1  0.93  17   IL  40.000000  -89.000000
12         Indiana    137        1  0.60  18   IN  40.273502  -86.126976
13            Iowa    126        1  1.13  19   IA  42.032974  -93.581543
14          Kansas    237        1  2.37  20   KS  38.500000  -98.000000
15        Kentucky    139        1  0.91  21   KY  37.839333  -84.270020
16       Louisiana    225        1  1.36  22   LA  30.391830  -92.329102
17           Maine     10        0  0.42  23   ME  45.367584  -68.972168
18        Maryland    162        0  0.80  24   MD  39.045753  -76.641273
19   Massachusetts     28        1  0.24  25   MA  42.407211  -71.382439
20        Michigan    128        1  0.35  26   MI  44.182205  -84.506836
21       Minnesota     57        1  0.61  27   MN  46.392410  -94.636230
22     Mississippi    175        1  1.66  28   MS  33.000000  -90.000000
23        Missouri    700        1  3.36  29   MO  38.573936  -92.603760
24         Montana     14        0  0.81  30   MT  46.965260 -109.533691
25        Nebraska     47        0  0.73  31   NE  41.500000 -100.000000
26          Nevada    251        1  3.18  32   NV  39.876019 -117.224121
27   New Hampshire     10        0  0.43  33   NH  44.000000  -71.500000
28      New Jersey    117        0  0.37  34   NJ  39.833851  -74.871826
29      New Mexico     55        1  1.55  35   NM  34.307144 -106.018066
30        New York    314        1  0.45  36   NY  43.000000  -75.000000
31  North Carolina    206        1  0.66  37   NC  35.782169  -80.793457
32            Ohio    185        1  0.44  39   OH  40.367474  -82.996216
33        Oklahoma    282        1  2.15  40   OK  36.084621  -96.921387
34          Oregon     65        1  0.52  41   OR  44.000000 -120.500000
35    Pennsylvania    290        1  0.63  42   PA  41.203323  -77.194527
36    Rhode Island     10        0  0.53  44   RI  41.742325  -71.742332
37  South Carolina    243        1  1.62  45   SC  33.836082  -81.163727
38    South Dakota     22        1  1.53  46   SD  44.500000 -100.000000
39       Tennessee    233        1  1.08  47   TN  35.860119  -86.660156
40           Texas   1127        1  1.38  48   TX  31.000000 -100.000000
41            Utah     37        0  0.46  49   UT  39.419220 -111.950684
42        Virginia    195        1  0.72  51   VA  37.926868  -78.024902
43      Washington     88        0  0.39  53   WA  47.751076 -120.740135
44   West Virginia     11        0  0.33  54   WV  39.000000  -80.500000
45       Wisconsin    152        1  0.76  55   WI  44.500000  -89.500000

In [19]:
# base2 = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

deltdf=mergeWansi(funcdelta(1979,2016,plotdf))

chart2 = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color=alt.Color('temperature:Q',scale=alt.Scale(scheme='orangered'),title='Temp Change in Degrees Celsius'),
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(deltdf, 'id', ['temperature'])
).properties(
    width=500,
    height=300
).project('albersUsa')


points = alt.Chart(wansi_cleanDF).mark_circle().encode(
    longitude='longitude:Q',
    latitude='latitude:Q',
    size=alt.Size('Deaths:Q', title='Number of Heat Related Deaths'),
    color=alt.value('black')
).properties(
    title='Number of Heat Related Deaths in the US from 1979 to 2016'
)

chart2+points

alt.LayerChart(...)

In [20]:
# base2 = alt.Chart(states).mark_geoshape(fill='lightgray', stroke='black', strokeWidth=0.5)

deltdf=mergeWansi(funcdelta(1979,2016,plotdf))

chart2 = alt.Chart(states).mark_geoshape(stroke='black').encode(
    color=alt.Color('temperature:Q',scale=alt.Scale(scheme='orangered'),title='Temp Change in Degrees Celsius'),
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(deltdf, 'id', ['temperature'])
).properties(
    width=500,
    height=300
).project('albersUsa')


points = alt.Chart(wansi_cleanDF).mark_circle().encode(
    longitude='longitude:Q',
    latitude='latitude:Q',
    size=alt.Size('DPM:Q', title='Number of Deaths'),
    color=alt.value('black'),
    tooltip='state'
).properties(
    title='Number of Heat Related Deaths per Million in the US from 1979 to 2016'
)

chart2+points

alt.LayerChart(...)